<?php

namespace App\Command;

use App\Entity\Fighter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:fighters',
    description: 'Add a short description for your command',
)]
class FightersCommand extends Command
{
    public function __construct(
        private EntityManagerInterface $entityManager,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addArgument('arg1', InputArgument::OPTIONAL, 'Argument description')
            ->addOption('option1', null, InputOption::VALUE_NONE, 'Option description')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // $io = new SymfonyStyle($input, $output);
        // $arg1 = $input->getArgument('arg1');

        // if ($arg1) {
        //     $io->note(sprintf('You passed an argument: %s', $arg1));
        // }

        // if ($input->getOption('option1')) {
        //     // ...
        // }

        // $io->success('You have a new command! Now make it your own! Pass --help to see your options.');

        $fighters = [
            [
                'name' => 'Jon Jones',
                'nickname' => 'Bones',
                'description' => 'Former UFC Light Heavyweight and Heavyweight Champion, considered one of the greatest fighters of all time',
                'weightClass' => 'Heavyweight',
                'wins' => 27,
                'losses' => 1,
                'draws' => 0,
                'noContest' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '19/07/1987',
                'placeOfBirth' => 'Rochester, New York, USA',
                'isActive' => true,
                'height' => 193,
                'weight' => 112,
                'reach' => 215,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Khabib Nurmagomedov',
                'nickname' => 'The Eagle',
                'description' => 'Former UFC Lightweight Champion, undefeated in professional MMA',
                'weightClass' => 'Lightweight',
                'wins' => 29,
                'losses' => 0,
                'draws' => 0,
                'noContest' => 0,
                'noContest' => 0,
                'country' => 'Russia',
                'birthday' => '20/09/1988',
                'placeOfBirth' => 'Sildi, Dagestan, Russia',
                'isActive' => false,
                'height' => 178,
                'weight' => 70,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Sambo',
            ],
            [
                'name' => 'Anderson Silva',
                'nickname' => 'The Spider',
                'description' => 'Former UFC Middleweight Champion, one of the most dominant champions in UFC history',
                'weightClass' => 'Middleweight',
                'wins' => 34,
                'losses' => 11,
                'draws' => 0,
                'noContest' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '14/04/1975',
                'placeOfBirth' => 'São Paulo, Brazil',
                'isActive' => false,
                'height' => 188,
                'weight' => 84,
                'reach' => 198,
                'stance' => 'Orthodox',
                'style' => 'Muay Thai',
            ],
            [
                'name' => 'Georges St-Pierre',
                'nickname' => 'Rush',
                'description' => 'Former UFC Welterweight and Middleweight Champion, considered one of the greatest fighters ever',
                'weightClass' => 'Welterweight',
                'wins' => 26,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'noContest' => 0,
                'country' => 'Canada',
                'birthday' => '19/05/1981',
                'placeOfBirth' => 'Saint-Isidore, Quebec, Canada',
                'isActive' => false,
                'height' => 178,
                'weight' => 77,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Conor McGregor',
                'nickname' => 'The Notorious',
                'description' => 'Former UFC Featherweight and Lightweight Champion, one of the biggest stars in UFC history',
                'weightClass' => 'Lightweight',
                'wins' => 22,
                'losses' => 6,
                'draws' => 0,
                'noContest' => 0,
                'noContest' => 0,
                'country' => 'Ireland',
                'birthday' => '14/07/1988',
                'placeOfBirth' => 'Dublin, Ireland',
                'isActive' => true,
                'height' => 175,
                'weight' => 70,
                'reach' => 188,
                'stance' => 'Southpaw',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Israel Adesanya',
                'nickname' => 'The Last Stylebender',
                'description' => 'Current UFC Middleweight Champion, former kickboxing champion',
                'weightClass' => 'Middleweight',
                'wins' => 24,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'New Zealand',
                'birthday' => '22/07/1989',
                'isActive' => true,
                'height' => 193,
                'weight' => 84,
                'reach' => 203,
                'stance' => 'Orthodox',
                'style' => 'Kickboxing',
            ],
            [
                'name' => 'Kamaru Usman',
                'nickname' => 'The Nigerian Nightmare',
                'description' => 'Former UFC Welterweight Champion, one of the most dominant champions in recent history',
                'weightClass' => 'Welterweight',
                'wins' => 20,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Nigeria',
                'birthday' => '11/05/1987',
                'isActive' => true,
                'height' => 183,
                'weight' => 77,
                'reach' => 193,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Amanda Nunes',
                'nickname' => 'The Lioness',
                'description' => 'Former UFC Bantamweight and Featherweight Champion, considered the greatest female fighter of all time',
                'weightClass' => 'Bantamweight',
                'wins' => 23,
                'losses' => 5,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '30/05/1988',
                'isActive' => true,
                'height' => 173,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Valentina Shevchenko',
                'nickname' => 'Bullet',
                'description' => 'Former UFC Flyweight Champion, former kickboxing and Muay Thai champion',
                'weightClass' => 'Flyweight',
                'wins' => 23,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Kyrgyzstan',
                'birthday' => '07/03/1988',
                'isActive' => true,
                'height' => 165,
                'weight' => 57,
                'reach' => 168,
                'stance' => 'Orthodox',
                'style' => 'Muay Thai',
            ],
            [
                'name' => 'Francis Ngannou',
                'nickname' => 'The Predator',
                'description' => 'Former UFC Heavyweight Champion, known for his devastating knockout power',
                'weightClass' => 'Heavyweight',
                'wins' => 17,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Cameroon',
                'birthday' => '05/09/1986',
                'isActive' => false,
                'height' => 193,
                'weight' => 120,
                'reach' => 211,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Charles Oliveira',
                'nickname' => 'Do Bronx',
                'description' => 'Former UFC Lightweight Champion, holds the record for most submission wins in UFC history',
                'weightClass' => 'Lightweight',
                'wins' => 34,
                'losses' => 9,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '17/10/1989',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Dustin Poirier',
                'nickname' => 'The Diamond',
                'description' => 'Former UFC Interim Lightweight Champion, known for his exciting fighting style',
                'weightClass' => 'Lightweight',
                'wins' => 29,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '19/01/1989',
                'isActive' => true,
                'height' => 175,
                'weight' => 70,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Justin Gaethje',
                'nickname' => 'The Highlight',
                'description' => 'Former UFC Interim Lightweight Champion, known for his aggressive fighting style',
                'weightClass' => 'Lightweight',
                'wins' => 24,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '14/11/1988',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Islam Makhachev',
                'nickname' => 'The Eagle',
                'description' => 'Current UFC Lightweight Champion, training partner of Khabib Nurmagomedov',
                'weightClass' => 'Lightweight',
                'wins' => 24,
                'losses' => 1,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Russia',
                'birthday' => '27/10/1991',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Sambo',
            ],
            [
                'name' => 'Alexander Volkanovski',
                'nickname' => 'The Great',
                'description' => 'Current UFC Featherweight Champion, former rugby player',
                'weightClass' => 'Featherweight',
                'wins' => 25,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Australia',
                'birthday' => '29/09/1988',
                'isActive' => true,
                'height' => 168,
                'weight' => 66,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Max Holloway',
                'nickname' => 'Blessed',
                'description' => 'Former UFC Featherweight Champion, known for his volume striking',
                'weightClass' => 'Featherweight',
                'wins' => 23,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '04/12/1991',
                'isActive' => true,
                'height' => 180,
                'weight' => 66,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Aljamain Sterling',
                'nickname' => 'Funk Master',
                'description' => 'Former UFC Bantamweight Champion, known for his wrestling and grappling',
                'weightClass' => 'Bantamweight',
                'wins' => 23,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '31/07/1989',
                'isActive' => true,
                'height' => 168,
                'weight' => 61,
                'reach' => 168,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Petr Yan',
                'nickname' => 'No Mercy',
                'description' => 'Former UFC Bantamweight Champion, known for his technical striking',
                'weightClass' => 'Bantamweight',
                'wins' => 16,
                'losses' => 5,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Russia',
                'birthday' => '11/02/1993',
                'isActive' => true,
                'height' => 170,
                'weight' => 61,
                'reach' => 170,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Sean O\'Malley',
                'nickname' => 'Sugar',
                'description' => 'Current UFC Bantamweight Champion, known for his colorful personality and striking',
                'weightClass' => 'Bantamweight',
                'wins' => 17,
                'losses' => 1,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '24/10/1994',
                'isActive' => true,
                'height' => 178,
                'weight' => 61,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Deiveson Figueiredo',
                'nickname' => 'Deus da Guerra',
                'description' => 'Former UFC Flyweight Champion, known for his power and aggression',
                'weightClass' => 'Flyweight',
                'wins' => 21,
                'losses' => 3,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '18/12/1987',
                'isActive' => true,
                'height' => 165,
                'weight' => 57,
                'reach' => 168,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Brandon Moreno',
                'nickname' => 'The Assassin Baby',
                'description' => 'Former UFC Flyweight Champion, first Mexican-born UFC champion',
                'weightClass' => 'Flyweight',
                'wins' => 21,
                'losses' => 7,
                'draws' => 2,
                'noContest' => 0,
                'country' => 'Mexico',
                'birthday' => '07/12/1993',
                'isActive' => true,
                'height' => 168,
                'weight' => 57,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Alex Pereira',
                'nickname' => 'Poatan',
                'description' => 'Current UFC Light Heavyweight Champion, former kickboxing champion',
                'weightClass' => 'Light Heavyweight',
                'wins' => 9,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '07/07/1987',
                'isActive' => true,
                'height' => 193,
                'weight' => 93,
                'reach' => 203,
                'stance' => 'Orthodox',
                'style' => 'Kickboxing',
            ],
            [
                'name' => 'Jiri Prochazka',
                'nickname' => 'BJP',
                'description' => 'Former UFC Light Heavyweight Champion, known for his unorthodox fighting style',
                'weightClass' => 'Light Heavyweight',
                'wins' => 29,
                'losses' => 4,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'Czech Republic',
                'birthday' => '14/10/1992',
                'isActive' => true,
                'height' => 193,
                'weight' => 93,
                'reach' => 203,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Jan Blachowicz',
                'nickname' => 'Legendary Polish Power',
                'description' => 'Former UFC Light Heavyweight Champion, known for his knockout power',
                'weightClass' => 'Light Heavyweight',
                'wins' => 29,
                'losses' => 10,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'Poland',
                'birthday' => '24/02/1983',
                'isActive' => true,
                'height' => 188,
                'weight' => 93,
                'reach' => 198,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Glover Teixeira',
                'nickname' => 'The Brazilian Pitbull',
                'description' => 'Former UFC Light Heavyweight Champion, known for his grappling',
                'weightClass' => 'Light Heavyweight',
                'wins' => 33,
                'losses' => 9,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '28/10/1979',
                'isActive' => true,
                'height' => 188,
                'weight' => 93,
                'reach' => 193,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Curtis Blaydes',
                'nickname' => 'Razor',
                'description' => 'Top-ranked UFC Heavyweight, known for his wrestling',
                'weightClass' => 'Heavyweight',
                'wins' => 17,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '18/02/1991',
                'isActive' => true,
                'height' => 193,
                'weight' => 120,
                'reach' => 203,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Ciryl Gane',
                'nickname' => 'Bon Gamin',
                'description' => 'Former UFC Interim Heavyweight Champion, former kickboxer',
                'weightClass' => 'Heavyweight',
                'wins' => 12,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'France',
                'birthday' => '12/04/1990',
                'isActive' => true,
                'height' => 196,
                'weight' => 120,
                'reach' => 208,
                'stance' => 'Orthodox',
                'style' => 'Kickboxing',
            ],
            [
                'name' => 'Tom Aspinall',
                'nickname' => 'The Asp',
                'description' => 'Current UFC Heavyweight Champion, known for his speed and athleticism',
                'weightClass' => 'Heavyweight',
                'wins' => 14,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'England',
                'birthday' => '11/04/1993',
                'isActive' => true,
                'height' => 198,
                'weight' => 120,
                'reach' => 203,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Leon Edwards',
                'nickname' => 'Rocky',
                'description' => 'Current UFC Welterweight Champion, known for his striking and clinch work',
                'weightClass' => 'Welterweight',
                'wins' => 22,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'England',
                'birthday' => '13/08/1991',
                'isActive' => true,
                'height' => 183,
                'weight' => 77,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Colby Covington',
                'nickname' => 'Chaos',
                'description' => 'Former UFC Interim Welterweight Champion, known for his wrestling and cardio',
                'weightClass' => 'Welterweight',
                'wins' => 17,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '22/02/1988',
                'isActive' => true,
                'height' => 180,
                'weight' => 77,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Belal Muhammad',
                'nickname' => 'Remember the Name',
                'description' => 'Top-ranked UFC Welterweight, known for his wrestling and pressure',
                'weightClass' => 'Welterweight',
                'wins' => 23,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '09/07/1988',
                'isActive' => true,
                'height' => 178,
                'weight' => 77,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Shavkat Rakhmonov',
                'nickname' => 'Nomad',
                'description' => 'Top-ranked UFC Welterweight, undefeated with all wins by finish',
                'weightClass' => 'Welterweight',
                'wins' => 17,
                'losses' => 0,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Kazakhstan',
                'birthday' => '23/10/1994',
                'isActive' => true,
                'height' => 183,
                'weight' => 77,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Robert Whittaker',
                'nickname' => 'The Reaper',
                'description' => 'Former UFC Middleweight Champion, known for his striking and takedown defense',
                'weightClass' => 'Middleweight',
                'wins' => 24,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Australia',
                'birthday' => '20/12/1990',
                'isActive' => true,
                'height' => 183,
                'weight' => 84,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Marvin Vettori',
                'nickname' => 'The Italian Dream',
                'description' => 'Top-ranked UFC Middleweight, known for his grappling and pressure',
                'weightClass' => 'Middleweight',
                'wins' => 19,
                'losses' => 7,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'Italy',
                'birthday' => '20/09/1993',
                'isActive' => true,
                'height' => 183,
                'weight' => 84,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Paulo Costa',
                'nickname' => 'Borrachinha',
                'description' => 'Top-ranked UFC Middleweight, known for his power and aggression',
                'weightClass' => 'Middleweight',
                'wins' => 14,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '21/04/1991',
                'isActive' => true,
                'height' => 183,
                'weight' => 84,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Jared Cannonier',
                'nickname' => 'The Killa Gorilla',
                'description' => 'Top-ranked UFC Middleweight, former heavyweight',
                'weightClass' => 'Middleweight',
                'wins' => 17,
                'losses' => 6,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '16/03/1984',
                'isActive' => true,
                'height' => 180,
                'weight' => 84,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Sean Strickland',
                'nickname' => 'Tarzan',
                'description' => 'Former UFC Middleweight Champion, known for his unorthodox style',
                'weightClass' => 'Middleweight',
                'wins' => 28,
                'losses' => 5,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '27/02/1991',
                'isActive' => true,
                'height' => 185,
                'weight' => 84,
                'reach' => 193,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Dricus Du Plessis',
                'nickname' => 'Stillknocks',
                'description' => 'Current UFC Middleweight Champion, first South African UFC champion',
                'weightClass' => 'Middleweight',
                'wins' => 21,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'South Africa',
                'birthday' => '14/01/1994',
                'isActive' => true,
                'height' => 183,
                'weight' => 84,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Khamzat Chimaev',
                'nickname' => 'Borz',
                'description' => 'Top-ranked UFC fighter, known for his dominant wrestling and grappling',
                'weightClass' => 'Middleweight',
                'wins' => 13,
                'losses' => 0,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Sweden',
                'birthday' => '01/05/1994',
                'isActive' => true,
                'height' => 188,
                'weight' => 84,
                'reach' => 193,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Beneil Dariush',
                'nickname' => 'Benny',
                'description' => 'Top-ranked UFC Lightweight, known for his grappling and submissions',
                'weightClass' => 'Lightweight',
                'wins' => 22,
                'losses' => 5,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '06/05/1989',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Arman Tsarukyan',
                'nickname' => 'Ahalkalakets',
                'description' => 'Top-ranked UFC Lightweight, known for his wrestling and grappling',
                'weightClass' => 'Lightweight',
                'wins' => 20,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Armenia',
                'birthday' => '11/10/1996',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Mateusz Gamrot',
                'nickname' => 'Gamer',
                'description' => 'Top-ranked UFC Lightweight, known for his wrestling and grappling',
                'weightClass' => 'Lightweight',
                'wins' => 23,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Poland',
                'birthday' => '11/12/1990',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Dan Hooker',
                'nickname' => 'The Hangman',
                'description' => 'Top-ranked UFC Lightweight, known for his striking and toughness',
                'weightClass' => 'Lightweight',
                'wins' => 22,
                'losses' => 12,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'New Zealand',
                'birthday' => '13/02/1990',
                'isActive' => true,
                'height' => 183,
                'weight' => 70,
                'reach' => 193,
                'stance' => 'Orthodox',
                'style' => 'Kickboxing',
            ],
            [
                'name' => 'Rafael Fiziev',
                'nickname' => 'Ataman',
                'description' => 'Top-ranked UFC Lightweight, former Muay Thai champion',
                'weightClass' => 'Lightweight',
                'wins' => 12,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Azerbaijan',
                'birthday' => '05/03/1993',
                'isActive' => true,
                'height' => 175,
                'weight' => 70,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Muay Thai',
            ],
            [
                'name' => 'Jalin Turner',
                'nickname' => 'The Tarantula',
                'description' => 'Top-ranked UFC Lightweight, known for his length and striking',
                'weightClass' => 'Lightweight',
                'wins' => 14,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '18/05/1995',
                'isActive' => true,
                'height' => 188,
                'weight' => 70,
                'reach' => 198,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Grant Dawson',
                'nickname' => 'KGD',
                'description' => 'Top-ranked UFC Lightweight, known for his wrestling and grappling',
                'weightClass' => 'Lightweight',
                'wins' => 20,
                'losses' => 1,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '20/02/1994',
                'isActive' => true,
                'height' => 178,
                'weight' => 70,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Yair Rodriguez',
                'nickname' => 'El Pantera',
                'description' => 'Former UFC Interim Featherweight Champion, known for his creative striking',
                'weightClass' => 'Featherweight',
                'wins' => 15,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Mexico',
                'birthday' => '06/10/1992',
                'isActive' => true,
                'height' => 178,
                'weight' => 66,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Brian Ortega',
                'nickname' => 'T-City',
                'description' => 'Top-ranked UFC Featherweight, known for his submissions',
                'weightClass' => 'Featherweight',
                'wins' => 15,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '21/02/1991',
                'isActive' => true,
                'height' => 173,
                'weight' => 66,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Josh Emmett',
                'nickname' => 'The Fighting Falmer',
                'description' => 'Top-ranked UFC Featherweight, known for his power',
                'weightClass' => 'Featherweight',
                'wins' => 18,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '04/03/1985',
                'isActive' => true,
                'height' => 168,
                'weight' => 66,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Arnold Allen',
                'nickname' => 'Almighty',
                'description' => 'Top-ranked UFC Featherweight, undefeated in UFC until 2023',
                'weightClass' => 'Featherweight',
                'wins' => 19,
                'losses' => 2,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'England',
                'birthday' => '22/01/1994',
                'isActive' => true,
                'height' => 173,
                'weight' => 66,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Calvin Kattar',
                'nickname' => 'The Boston Finisher',
                'description' => 'Top-ranked UFC Featherweight, known for his boxing',
                'weightClass' => 'Featherweight',
                'wins' => 23,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '26/03/1988',
                'isActive' => true,
                'height' => 178,
                'weight' => 66,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Giga Chikadze',
                'nickname' => 'Ninja',
                'description' => 'Top-ranked UFC Featherweight, former kickboxer',
                'weightClass' => 'Featherweight',
                'wins' => 15,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Georgia',
                'birthday' => '08/08/1988',
                'isActive' => true,
                'height' => 183,
                'weight' => 66,
                'reach' => 188,
                'stance' => 'Orthodox',
                'style' => 'Kickboxing',
            ],
            [
                'name' => 'Bryce Mitchell',
                'nickname' => 'Thug Nasty',
                'description' => 'Top-ranked UFC Featherweight, known for his grappling',
                'weightClass' => 'Featherweight',
                'wins' => 16,
                'losses' => 1,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '04/10/1994',
                'isActive' => true,
                'height' => 173,
                'weight' => 66,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Movsar Evloev',
                'nickname' => 'The Eagle',
                'description' => 'Top-ranked UFC Featherweight, undefeated in MMA',
                'weightClass' => 'Featherweight',
                'wins' => 17,
                'losses' => 0,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Russia',
                'birthday' => '21/02/1994',
                'isActive' => true,
                'height' => 173,
                'weight' => 66,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Sodiq Yusuff',
                'nickname' => 'Super',
                'description' => 'Top-ranked UFC Featherweight, known for his striking',
                'weightClass' => 'Featherweight',
                'wins' => 13,
                'losses' => 3,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Nigeria',
                'birthday' => '19/05/1993',
                'isActive' => true,
                'height' => 175,
                'weight' => 66,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Merab Dvalishvili',
                'nickname' => 'The Machine',
                'description' => 'Top-ranked UFC Bantamweight, known for his wrestling and cardio',
                'weightClass' => 'Bantamweight',
                'wins' => 16,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Georgia',
                'birthday' => '10/04/1991',
                'isActive' => true,
                'height' => 168,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Cory Sandhagen',
                'nickname' => 'The Sandman',
                'description' => 'Top-ranked UFC Bantamweight, known for his creative striking',
                'weightClass' => 'Bantamweight',
                'wins' => 16,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '20/04/1992',
                'isActive' => true,
                'height' => 175,
                'weight' => 61,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Rob Font',
                'nickname' => 'The Boston Finisher',
                'description' => 'Top-ranked UFC Bantamweight, known for his boxing',
                'weightClass' => 'Bantamweight',
                'wins' => 20,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '25/06/1987',
                'isActive' => true,
                'height' => 173,
                'weight' => 61,
                'reach' => 183,
                'stance' => 'Orthodox',
                'style' => 'Boxing',
            ],
            [
                'name' => 'Marlon Vera',
                'nickname' => 'Chito',
                'description' => 'Top-ranked UFC Bantamweight, known for his toughness and striking',
                'weightClass' => 'Bantamweight',
                'wins' => 23,
                'losses' => 8,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'Ecuador',
                'birthday' => '02/12/1992',
                'isActive' => true,
                'height' => 173,
                'weight' => 61,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Song Yadong',
                'nickname' => 'Kung Fu Monkey',
                'description' => 'Top-ranked UFC Bantamweight, known for his striking',
                'weightClass' => 'Bantamweight',
                'wins' => 20,
                'losses' => 7,
                'draws' => 1,
                'noContest' => 0,
                'country' => 'China',
                'birthday' => '02/12/1997',
                'isActive' => true,
                'height' => 170,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Dominick Cruz',
                'nickname' => 'The Dominator',
                'description' => 'Former UFC Bantamweight Champion, known for his footwork and movement',
                'weightClass' => 'Bantamweight',
                'wins' => 24,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '09/03/1985',
                'isActive' => true,
                'height' => 173,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Mixed Martial Arts',
            ],
            [
                'name' => 'Pedro Munhoz',
                'nickname' => 'The Young Punisher',
                'description' => 'Top-ranked UFC Bantamweight, known for his leg kicks',
                'weightClass' => 'Bantamweight',
                'wins' => 20,
                'losses' => 7,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Brazil',
                'birthday' => '19/09/1986',
                'isActive' => true,
                'height' => 168,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Brazilian Jiu-Jitsu',
            ],
            [
                'name' => 'Ricky Simon',
                'nickname' => 'The Dirty Sprite',
                'description' => 'Top-ranked UFC Bantamweight, known for his wrestling',
                'weightClass' => 'Bantamweight',
                'wins' => 20,
                'losses' => 4,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'USA',
                'birthday' => '06/08/1992',
                'isActive' => true,
                'height' => 168,
                'weight' => 61,
                'reach' => 175,
                'stance' => 'Orthodox',
                'style' => 'Wrestling',
            ],
            [
                'name' => 'Umar Nurmagomedov',
                'nickname' => 'Young Eagle',
                'description' => 'Top-ranked UFC Bantamweight, cousin of Khabib Nurmagomedov',
                'weightClass' => 'Bantamweight',
                'wins' => 16,
                'losses' => 0,
                'draws' => 0,
                'noContest' => 0,
                'country' => 'Russia',
                'birthday' => '03/01/1996',
                'isActive' => true,
                'height' => 173,
                'weight' => 61,
                'reach' => 178,
                'stance' => 'Orthodox',
                'style' => 'Sambo',
            ],
        ];

        foreach ($fighters as $fighterData) {
            $fighter = new Fighter();
            $fighter->setName($fighterData['name']);
            $fighter->setNickname($fighterData['nickname']);
            $fighter->setDescription($fighterData['description']);
            $fighter->setWeightClass($fighterData['weightClass']);
            $fighter->setWins($fighterData['wins']);
            $fighter->setLosses($fighterData['losses']);
            $fighter->setDraws($fighterData['draws']);
            $fighter->setCountry($fighterData['country']);
            $fighter->setBirthday(\DateTime::createFromFormat('d/m/Y', $fighterData['birthday']));
            $fighter->setPlaceOfBirth($fighterData['placeOfBirth'] ?? null);
            $fighter->setNoContest(!empty($fighterData['noContest']) ? $fighterData['noContest'] : 0);
            $fighter->setIsActive($fighterData['isActive']);
            $fighter->setHeight($fighterData['height']);
            $fighter->setWeight($fighterData['weight']);
            $fighter->setReach($fighterData['reach']);
            $fighter->setStance($fighterData['stance']);
            $fighter->setStyle($fighterData['style']);
            $this->entityManager->persist($fighter);
            $this->entityManager->flush();
        }

        return Command::SUCCESS;
    }
}
