nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
            - '^https?://.*\.stripe\.com$'
            - '^https://checkout\.stripe\.com$'
            - '^https://api\.stripe\.com$'
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With', 'X-XSRF-TOKEN', 'Stripe-Signature']
        expose_headers: ['Link', 'X-XSRF-TOKEN']
        max_age: 3600
    paths:
        '^/': ~
